# Generated by Django 3.0.5 on 2020-04-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lovely',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트 시간')),
                ('image', models.ImageField(default='lovely/default/photo.png', upload_to='lovely/img/', verbose_name='이미지')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
